# This is a basic workflow to help you get started with Actions
name: Deploy Application

# Controls when the workflow will run
on:

  # Triggers the workflow on push request events but only for the develop branch
  push:
    branches: [ main ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  app-tests:
    runs-on: ubuntu-latest
    services:
        mysql:
          image: postgres:9.6
          
          ports:
            - 5432

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: shivammathur/setup-python@v2
        with:
          python-version: 3.9
          
